curr_fig = figure;
[freq_spectra_data, ~, ~, ~] = pop_spectopo(processed_EEG, 1, ...
[processed_EEG.xmin (processed_EEG.xmax*1000)], ...
'EEG' , 'freqrange', [0.5, 30], 'electrodes', 'off');
close(curr_fig);